spring:

  application:
    name: auth-service
  datasource:
          url: ${DB_URL}
          username: ${DB_USERNAME"}
          password: ${DB_PASSWORD}
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "optional:configserver:http://localhost:8888" # Points to your Config Server
  cloud:
    config:
      fail-fast: true
logging:
  level:
    org.apache.kafka.clients.producer: DEBUG

un: dev
server:
  port: 8050







